In [1]:
import pandas as pd
import numpy as np

In [2]:
installs = pd.read_csv('installs.csv.gzip', compression = 'gzip', dtype ={'click_hash': object, 'wifi': object, 'trans_id': object})

In [3]:
# No tiene sentido quedarse con el pais, porque es uno solo
#No tiene sentido quedarse con la columna trans_id. El 98% de los valores son Null
#No tiene sentido quedarse con click_hash, el 99% de los valors son null
#No tiene sentido quedarse con event_uuid, el 78% de los valores son null
#No tiene sentido quedarse con kind, el 78% de los valores son null
#No tiene sentido quedarse con wifi, el 48% de los valores son null
#No tiene sentido quedarse con device_brand. El 42% son null
#No tiene sentido quedarse con la columna user_agent El 31% de los valores son Null
#¿Tiene sentido quedarse con la columna session_user_agent? El 3% de los valores son Null
# session_user_agent tiene el 3% de los valores null. Borro esas filas
del installs['trans_id']
del installs['device_countrycode']
del installs['click_hash']
del installs['event_uuid']
del installs['kind']
del installs['wifi']
del installs['device_brand']
del installs['user_agent']
del installs['session_user_agent']

##Borro las filas que tienen null en device_model y device_language. Juntas son el 5% de las filas en null
installs = installs[pd.notnull(installs['device_model'])]
installs = installs[pd.notnull(installs['device_language'])]

In [4]:
installs['created'] = pd.to_datetime(installs['created'], errors = 'coerce')

In [5]:
events = pd.read_csv('events.csv.gzip', compression = 'gzip',
                     dtype={
                         'device_countrycode': 'category', 
                         'device_city': 'category',
                         'ref_type': 'category',
                         'application_id': 'uint16',
                         'device_os_version': 'category',
                         'device_brand': 'category',
                         'device_model': 'category',
                         'session_user_agent': 'category',
                         'trans_id': 'category',
                         'user_agent': 'category',
                         'carrier': 'category',
                         'device_os': 'category',
                         'device_os_version': 'category',
                         'device_language': 'category',
                         'connection_type': 'category',
                         'wifi': 'category'
                     })

In [6]:
del events['device_countrycode'] #Borrada porque hay un solo país
del events['trans_id'] #Borrada por tener muy pocos valores (37000/7000000)
del events['event_uuid'] #Borrada por tener todos los valores distintos
del events['device_os_version'] #Borrado por tener 70% de los valores nulos.
del events['device_brand'] #Borrado por tener 67% de los valores nulos
del events['device_city'] #Borrado por tener 76% de los valores nulos
del events['user_agent'] #Borrado por tener 57% de los valores nulos
del events['carrier'] #Borrado por tener 75% de los valores nulos
del events['device_os'] #Borrado por tener 76% de los valores nulos
del events['connection_type'] #Borrado por tener 77% de los valores nulos
del events['device_language'] #Borrado por tener 27% de los valores nulos
#------------------------------------------------------------------
events = events[pd.notnull(events['session_user_agent'])] #Borrados las filas nulas (0,5%)
events = events[pd.notnull(events['kind'])] #Borrados las filas nulas (0,5%)
#------------------------------------------------------------------
events = events[pd.notnull(events['device_model'])] #Borrado por tener 27% de nulos, podria rellenarse si no andan los algoritmos

In [15]:
installs[installs['ref_hash'] == 5230323462636548010]

,created,application_id,ref_type,ref_hash,attributed,implicit,device_model,ip_address,device_language
2,2019-04-20 10:15:36.274,1,1494519392962156891,5230323462636548010,False,True,8.355496e+18,8291809486355890410,4.060930e+18

In [16]:
events[events['ref_hash'] == 5230323462636548010]

,index,date,event_id,ref_type,ref_hash,application_id,attributed,device_model,session_user_agent,kind,wifi,ip_address
5364757,29,2019-04-20 10:15:36.274,7,1494519392962156891,5230323462636548010,1,False,8.355495513718673e+18,7.164321382499455e+18,9.977660e+17,False,8291809486355890410

In [33]:
both = installs.merge(events[['ref_hash', 'wifi', 'session_user_agent']], on = 'ref_hash', how = 'inner')

In [34]:
both.head()

,created,application_id,ref_type,ref_hash,attributed,implicit,device_model,ip_address,device_language,wifi,session_user_agent
0,2019-04-24 06:23:29.495,1,1494519392962156891,4716708407362582887,False,True,3.739127e+17,4243443387795468703,3.301378e+18,False,7.164321382499455e+18
1,2019-04-20 10:15:36.274,1,1494519392962156891,5230323462636548010,False,True,8.355496e+18,8291809486355890410,4.060930e+18,False,7.164321382499455e+18
2,2019-04-20 21:56:47.151,1,1494519392962156891,5097163995161606833,False,True,2.355772e+18,4006811922873399949,3.301378e+18,True,3.819516403548394e+18
3,2019-04-20 21:56:47.151,1,1494519392962156891,5097163995161606833,False,True,2.355772e+18,4006811922873399949,3.301378e+18,False,7.164321382499455e+18
4,2019-04-20 21:56:47.151,1,1494519392962156891,5097163995161606833,False,True,2.355772e+18,4006811922873399949,3.301378e+18,True,3.819516403548394e+18