In [1]:
import pandas as pd
import numpy as np

In [2]:
#Para que esto funcione es mucho muy importante que los txt tengan en la primer linea escrito "obj"(sin comillas) y despues en la linea de abajo su primer
#prediccion y en la linea de abajo la siguiente y asi sucesivamente. Quedando como si fuera UNA columna con en nombre obj y cada fila una prediccion
st = "output/predicciones_st.csv"
sc = "output/predicciones_sc.csv"
resultado = "output/submission.csv"

In [3]:
target = pd.read_csv('datos/target_competencia_ids.csv', dtype ={'obj': 'int64'})

In [4]:
target.dtypes

ref_hash    object
obj          int64
dtype: object

In [5]:
target.head()

                 ref_hash  obj
0  1000169251625791246_sc    0
1  1000169251625791246_st    0
2  1000395625957344683_sc    0
3  1000395625957344683_st    0
4  1003027494996471685_sc    0

In [6]:
target.isnull().sum().sum()

0

In [7]:
targets_sc = target[target['ref_hash'].str.contains('_sc')]

In [8]:
targets_st = target[target['ref_hash'].str.contains('_st')]

In [9]:
targets_st.count()

ref_hash    4037
obj         4037
dtype: int64

In [10]:
targets_sc.count()

ref_hash    4037
obj         4037
dtype: int64

In [11]:
targets_st.isnull().sum().sum()

0

In [12]:
sc_pred = pd.read_csv(sc, header=None)
st_pred = pd.read_csv(st, header=None)

In [13]:
len(sc_pred)

4037

In [14]:
len(st_pred)

4037

In [15]:
sc_pred.dtypes

0    float64
dtype: object

In [16]:
st_pred.dtypes

0    float64
dtype: object

In [17]:
st_pred.index = np.arange(1, 8074, 2)

In [18]:
st_pred

              0
1     79299.820
3     79931.260
5     83127.500
7     80217.840
9     79299.820
11    83127.500
13    83134.820
15    82209.480
17    82209.480
19    79299.820
21    79299.820
23    79708.900
25    80334.480
27    83127.500
29    82209.480
31    79218.190
33    79709.840
35    80217.840
37    82216.800
39    83127.500
41    82619.500
43    80334.480
45    82209.480
47    82209.480
49    87877.230
51    79299.820
53    79298.875
55    80217.840
57    79299.820
59    79299.820
...         ...
8015  82619.460
8017  82626.820
8019  82626.820
8021  77056.930
8023  83127.500
8025  79709.840
8027  79299.820
8029  82216.800
8031  80217.805
8033  82209.440
8035  82619.460
8037  83127.460
8039  79904.900
8041  82209.440
8043  79299.780
8045  79299.780
8047  79904.900
8049  82209.440
8051  82814.555
8053  79299.780
8055  79389.950
8057  79299.780
8059  82209.440
8061  79299.780
8063  79834.770
8065  80506.240
8067  82848.234
8069  82619.500
8071  83127.500
8073  79299.820

[4037 rows x 1 columns]

In [19]:
sc_pred.index = np.arange(0, 8074, 2)

In [20]:
sc_pred

                  0
0     129754.989856
2     128698.471740
4     128299.371602
6     128518.230001
8      54623.733544
10    128518.230001
12    128438.044600
14    128649.875005
16    128518.230001
18    128491.523586
20    129257.644411
22    128649.875005
24    129257.644411
26    129078.623699
28    127900.845222
30    129139.187629
32    129078.623699
34    129281.614113
36    129281.614113
38    128077.516782
40    128077.516782
42    128518.230001
44    128518.230001
46    129257.644411
48    125767.252701
50    128649.875005
52    126811.149157
54    128518.230001
56    128649.875005
58    129040.985529
...             ...
8014  128649.875005
8016  129589.556870
8018  129666.492375
8020  127900.845222
8022  128518.230001
8024  129754.989856
8026  129257.644411
8028  130718.528657
8030  130223.779416
8032  128518.230001
8034  127174.332477
8036  129139.187629
8038  128649.875005
8040  126811.149157
8042  128518.230001
8044  129281.614113
8046  129281.614113
8048  129078.623699
8050  126576.587675
8052  128518.230001
8054  129193.375251
8056  130384.762761
8058  125767.252701
8060  129109.835342
8062  126811.149157
8064  128518.230001
8066  129524.407613
8068  128698.471740
8070  128491.523586
8072  129139.187629

[4037 rows x 1 columns]

In [21]:
targets_st['obj'] = st_pred
targets_sc['obj'] = sc_pred

/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/gabriel/workspace/7506-1c2019/env/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [22]:
targets_st.head()

                 ref_hash       obj
1  1000169251625791246_st  79299.82
3  1000395625957344683_st  79931.26
5  1003027494996471685_st  83127.50
7  1006670001679961544_st  80217.84
9  1007573308966476713_st  79299.82

In [23]:
targets_st

                    ref_hash        obj
1     1000169251625791246_st  79299.820
3     1000395625957344683_st  79931.260
5     1003027494996471685_st  83127.500
7     1006670001679961544_st  80217.840
9     1007573308966476713_st  79299.820
11    1010070503877148763_st  83127.500
13    1010265377387765028_st  83134.820
15    1010531372912327058_st  82209.480
17    1011610998357271358_st  82209.480
19    1013543838965040946_st  79299.820
21    1014428234021750342_st  79299.820
23     101763096421653092_st  79708.900
25    1017668882534236751_st  80334.480
27    1017958004932387739_st  83127.500
29    1018126962792619181_st  82209.480
31    1021582875881379650_st  79218.190
33    1022093956983448460_st  79709.840
35    1022155574388897311_st  80217.840
37    1024792555410741306_st  82216.800
39    1026825193119998092_st  83127.500
41    1030603044158081433_st  82619.500
43    1030865855693267844_st  80334.480
45    1032938399279723623_st  82209.480
47    1036919443887988520_st  82209.480
49       1037575899869926_st  87877.230
51    1042912100594917197_st  79299.820
53     104412862089502190_st  79298.875
55    1048460865075142817_st  80217.840
57    1048487908287530052_st  79299.820
59    1048782984015604883_st  79299.820
...                      ...        ...
8015   920133863974417940_st  82619.460
8017  9201763056911976665_st  82626.820
8019  9202591485087100048_st  82626.820
8021  9204600717983774215_st  77056.930
8023  9210211798524147977_st  83127.500
8025  9214306696431615228_st  79709.840
8027  9215274230034407241_st  79299.820
8029   923580934104999070_st  82216.800
8031   926513304015298690_st  80217.805
8033   928322998219934684_st  82209.440
8035   934102789941509295_st  82619.460
8037   940602545239263062_st  83127.460
8039   943221576691294743_st  79904.900
8041   947121781706964554_st  82209.440
8043   948984908655259886_st  79299.780
8045   950195972417607793_st  79299.780
8047   954110623376544206_st  79904.900
8049   954940018576714924_st  82209.440
8051   956704247780926402_st  82814.555
8053   960623204161846765_st  79299.780
8055   961631829441650729_st  79389.950
8057   962595921037755088_st  79299.780
8059   964658792449865522_st  82209.440
8061   974553511695777483_st  79299.780
8063    97694307709005918_st  79834.770
8065   977508757724050464_st  80506.240
8067   979880031097032355_st  82848.234
8069   987443249627191692_st  82619.500
8071   997953354533822687_st  83127.500
8073   998948062397755366_st  79299.820

[4037 rows x 2 columns]

In [24]:
target.head()

                 ref_hash  obj
0  1000169251625791246_sc    0
1  1000169251625791246_st    0
2  1000395625957344683_sc    0
3  1000395625957344683_st    0
4  1003027494996471685_sc    0

In [25]:
target.update(targets_sc)
target.update(targets_st)

In [26]:
target

                    ref_hash            obj
0     1000169251625791246_sc  129754.989856
1     1000169251625791246_st   79299.820000
2     1000395625957344683_sc  128698.471740
3     1000395625957344683_st   79931.260000
4     1003027494996471685_sc  128299.371602
5     1003027494996471685_st   83127.500000
6     1006670001679961544_sc  128518.230001
7     1006670001679961544_st   80217.840000
8     1007573308966476713_sc   54623.733544
9     1007573308966476713_st   79299.820000
10    1010070503877148763_sc  128518.230001
11    1010070503877148763_st   83127.500000
12    1010265377387765028_sc  128438.044600
13    1010265377387765028_st   83134.820000
14    1010531372912327058_sc  128649.875005
15    1010531372912327058_st   82209.480000
16    1011610998357271358_sc  128518.230001
17    1011610998357271358_st   82209.480000
18    1013543838965040946_sc  128491.523586
19    1013543838965040946_st   79299.820000
20    1014428234021750342_sc  129257.644411
21    1014428234021750342_st   79299.820000
22     101763096421653092_sc  128649.875005
23     101763096421653092_st   79708.900000
24    1017668882534236751_sc  129257.644411
25    1017668882534236751_st   80334.480000
26    1017958004932387739_sc  129078.623699
27    1017958004932387739_st   83127.500000
28    1018126962792619181_sc  127900.845222
29    1018126962792619181_st   82209.480000
...                      ...            ...
8044   950195972417607793_sc  129281.614113
8045   950195972417607793_st   79299.780000
8046   954110623376544206_sc  129281.614113
8047   954110623376544206_st   79904.900000
8048   954940018576714924_sc  129078.623699
8049   954940018576714924_st   82209.440000
8050   956704247780926402_sc  126576.587675
8051   956704247780926402_st   82814.555000
8052   960623204161846765_sc  128518.230001
8053   960623204161846765_st   79299.780000
8054   961631829441650729_sc  129193.375251
8055   961631829441650729_st   79389.950000
8056   962595921037755088_sc  130384.762761
8057   962595921037755088_st   79299.780000
8058   964658792449865522_sc  125767.252701
8059   964658792449865522_st   82209.440000
8060   974553511695777483_sc  129109.835342
8061   974553511695777483_st   79299.780000
8062    97694307709005918_sc  126811.149157
8063    97694307709005918_st   79834.770000
8064   977508757724050464_sc  128518.230001
8065   977508757724050464_st   80506.240000
8066   979880031097032355_sc  129524.407613
8067   979880031097032355_st   82848.234000
8068   987443249627191692_sc  128698.471740
8069   987443249627191692_st   82619.500000
8070   997953354533822687_sc  128491.523586
8071   997953354533822687_st   83127.500000
8072   998948062397755366_sc  129139.187629
8073   998948062397755366_st   79299.820000

[8074 rows x 2 columns]

In [27]:
target.to_csv(resultado, index = False)