In [28]:
import pandas as pd
import numpy as np

In [ ]:
#Para que esto funcione es mucho muy importante que los txt tengan en la primer linea escrito "obj"(sin comillas) y despues en la linea de abajo su primer
#prediccion y en la linea de abajo la siguiente y asi sucesivamente. Quedando como si fuera UNA columna con en nombre obj y cada fila una prediccion
st = "KNN-RF-XGBoost_St.txt"
sc = "NuevosFeatures_Sc2.txt"
resultado = "prediccionesKNN-RF-XGB-NuevasFeatures2.csv"

In [29]:
target = pd.read_csv('target_competencia_ids.csv', dtype ={'obj': 'int64'})

In [30]:
target.dtypes

ref_hash    object
obj          int64
dtype: object

In [31]:
target.head()

                 ref_hash  obj
0  1000169251625791246_sc    0
1  1000169251625791246_st    0
2  1000395625957344683_sc    0
3  1000395625957344683_st    0
4  1003027494996471685_sc    0

In [32]:
target.isnull().sum().sum()

0

In [33]:
targets_sc = target[target['ref_hash'].str.contains('_sc')]

In [34]:
targets_st = target[target['ref_hash'].str.contains('_st')]

In [35]:
targets_st.count()

ref_hash    4037
obj         4037
dtype: int64

In [36]:
targets_sc.count()

ref_hash    4037
obj         4037
dtype: int64

In [37]:
targets_st.isnull().sum().sum()

0

In [38]:
sc_pred = pd.read_csv(sc)
st_pred = pd.read_csv(st)

In [39]:
len(sc_pred)

4037

In [40]:
len(st_pred)

4037

In [41]:
sc_pred.dtypes

obj    float64
dtype: object

In [42]:
st_pred.dtypes

obj    float64
dtype: object

In [43]:
st_pred.index = np.arange(1, 8074, 2)

In [44]:
st_pred

            obj
1     79631.730
3     79679.830
5     82655.695
7     79636.414
9     79631.730
11    82655.695
13    82726.280
15    82651.010
17    82651.010
19    79631.730
21    79631.730
23    79658.240
25    82652.920
27    82655.695
29    82651.010
31    79633.640
33    79649.770
35    79636.414
37    83211.800
39    82655.695
41    82669.055
43    82652.920
45    82651.010
47    82651.010
49    88354.490
51    79631.730
53    79640.195
55    79636.414
57    79631.730
59    79631.730
...         ...
8015  82669.055
8017  82669.055
8019  82739.640
8021  79633.640
8023  82655.695
8025  79649.770
8027  79631.730
8029  83211.800
8031  79636.414
8033  82651.010
8035  82669.055
8037  79636.414
8039  79649.770
8041  79631.730
8043  79631.730
8045  79631.730
8047  79649.770
8049  79631.730
8051  82669.055
8053  79631.730
8055  79633.640
8057  79631.730
8059  82651.010
8061  79631.730
8063  79644.880
8065  82652.920
8067  82699.110
8069  82669.055
8071  82655.695
8073  79631.730

[4037 rows x 1 columns]

In [45]:
sc_pred.index = np.arange(0, 8074, 2)

In [46]:
sc_pred

             obj
0     130045.555
2     130911.660
4     129793.914
6     130920.460
8     129956.370
10    131127.860
12    129373.290
14    130515.290
16    131011.580
18    131074.110
20    130717.540
22    129614.020
24    131981.110
26    130921.250
28    131107.880
30    131671.520
32    130229.555
34    129373.290
36    130538.800
38    131074.110
40    132060.140
42    131052.016
44    131074.110
46    130795.070
48    130891.370
50    129589.530
52    126962.600
54    130866.720
56    131919.340
58    130703.160
...          ...
8014  130936.980
8016  131963.190
8018  130941.320
8020  132215.100
8022  131107.880
8024  132105.080
8026  129227.040
8028  130597.820
8030  131498.190
8032  130866.720
8034  129659.790
8036  131316.610
8038  129303.300
8040  126962.600
8042  131037.620
8044  132638.530
8046  132470.390
8048  129748.150
8050  130538.800
8052  131852.720
8054  129543.960
8056  133021.800
8058  130761.625
8060  131097.400
8062  126962.600
8064  130941.320
8066  131803.140
8068  130986.260
8070  131074.110
8072  131186.120

[4037 rows x 1 columns]

In [47]:
targets_st['obj'] = st_pred
targets_sc['obj'] = sc_pred

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [48]:
targets_st.head()

                 ref_hash        obj
1  1000169251625791246_st  79631.730
3  1000395625957344683_st  79679.830
5  1003027494996471685_st  82655.695
7  1006670001679961544_st  79636.414
9  1007573308966476713_st  79631.730

In [49]:
targets_st

                    ref_hash        obj
1     1000169251625791246_st  79631.730
3     1000395625957344683_st  79679.830
5     1003027494996471685_st  82655.695
7     1006670001679961544_st  79636.414
9     1007573308966476713_st  79631.730
11    1010070503877148763_st  82655.695
13    1010265377387765028_st  82726.280
15    1010531372912327058_st  82651.010
17    1011610998357271358_st  82651.010
19    1013543838965040946_st  79631.730
21    1014428234021750342_st  79631.730
23     101763096421653092_st  79658.240
25    1017668882534236751_st  82652.920
27    1017958004932387739_st  82655.695
29    1018126962792619181_st  82651.010
31    1021582875881379650_st  79633.640
33    1022093956983448460_st  79649.770
35    1022155574388897311_st  79636.414
37    1024792555410741306_st  83211.800
39    1026825193119998092_st  82655.695
41    1030603044158081433_st  82669.055
43    1030865855693267844_st  82652.920
45    1032938399279723623_st  82651.010
47    1036919443887988520_st  82651.010
49       1037575899869926_st  88354.490
51    1042912100594917197_st  79631.730
53     104412862089502190_st  79640.195
55    1048460865075142817_st  79636.414
57    1048487908287530052_st  79631.730
59    1048782984015604883_st  79631.730
...                      ...        ...
8015   920133863974417940_st  82669.055
8017  9201763056911976665_st  82669.055
8019  9202591485087100048_st  82739.640
8021  9204600717983774215_st  79633.640
8023  9210211798524147977_st  82655.695
8025  9214306696431615228_st  79649.770
8027  9215274230034407241_st  79631.730
8029   923580934104999070_st  83211.800
8031   926513304015298690_st  79636.414
8033   928322998219934684_st  82651.010
8035   934102789941509295_st  82669.055
8037   940602545239263062_st  79636.414
8039   943221576691294743_st  79649.770
8041   947121781706964554_st  79631.730
8043   948984908655259886_st  79631.730
8045   950195972417607793_st  79631.730
8047   954110623376544206_st  79649.770
8049   954940018576714924_st  79631.730
8051   956704247780926402_st  82669.055
8053   960623204161846765_st  79631.730
8055   961631829441650729_st  79633.640
8057   962595921037755088_st  79631.730
8059   964658792449865522_st  82651.010
8061   974553511695777483_st  79631.730
8063    97694307709005918_st  79644.880
8065   977508757724050464_st  82652.920
8067   979880031097032355_st  82699.110
8069   987443249627191692_st  82669.055
8071   997953354533822687_st  82655.695
8073   998948062397755366_st  79631.730

[4037 rows x 2 columns]

In [50]:
target.head()

                 ref_hash  obj
0  1000169251625791246_sc    0
1  1000169251625791246_st    0
2  1000395625957344683_sc    0
3  1000395625957344683_st    0
4  1003027494996471685_sc    0

In [51]:
target.update(targets_sc)
target.update(targets_st)

In [52]:
target

                    ref_hash         obj
0     1000169251625791246_sc  130045.555
1     1000169251625791246_st   79631.730
2     1000395625957344683_sc  130911.660
3     1000395625957344683_st   79679.830
4     1003027494996471685_sc  129793.914
5     1003027494996471685_st   82655.695
6     1006670001679961544_sc  130920.460
7     1006670001679961544_st   79636.414
8     1007573308966476713_sc  129956.370
9     1007573308966476713_st   79631.730
10    1010070503877148763_sc  131127.860
11    1010070503877148763_st   82655.695
12    1010265377387765028_sc  129373.290
13    1010265377387765028_st   82726.280
14    1010531372912327058_sc  130515.290
15    1010531372912327058_st   82651.010
16    1011610998357271358_sc  131011.580
17    1011610998357271358_st   82651.010
18    1013543838965040946_sc  131074.110
19    1013543838965040946_st   79631.730
20    1014428234021750342_sc  130717.540
21    1014428234021750342_st   79631.730
22     101763096421653092_sc  129614.020
23     101763096421653092_st   79658.240
24    1017668882534236751_sc  131981.110
25    1017668882534236751_st   82652.920
26    1017958004932387739_sc  130921.250
27    1017958004932387739_st   82655.695
28    1018126962792619181_sc  131107.880
29    1018126962792619181_st   82651.010
...                      ...         ...
8044   950195972417607793_sc  132638.530
8045   950195972417607793_st   79631.730
8046   954110623376544206_sc  132470.390
8047   954110623376544206_st   79649.770
8048   954940018576714924_sc  129748.150
8049   954940018576714924_st   79631.730
8050   956704247780926402_sc  130538.800
8051   956704247780926402_st   82669.055
8052   960623204161846765_sc  131852.720
8053   960623204161846765_st   79631.730
8054   961631829441650729_sc  129543.960
8055   961631829441650729_st   79633.640
8056   962595921037755088_sc  133021.800
8057   962595921037755088_st   79631.730
8058   964658792449865522_sc  130761.625
8059   964658792449865522_st   82651.010
8060   974553511695777483_sc  131097.400
8061   974553511695777483_st   79631.730
8062    97694307709005918_sc  126962.600
8063    97694307709005918_st   79644.880
8064   977508757724050464_sc  130941.320
8065   977508757724050464_st   82652.920
8066   979880031097032355_sc  131803.140
8067   979880031097032355_st   82699.110
8068   987443249627191692_sc  130986.260
8069   987443249627191692_st   82669.055
8070   997953354533822687_sc  131074.110
8071   997953354533822687_st   82655.695
8072   998948062397755366_sc  131186.120
8073   998948062397755366_st   79631.730

[8074 rows x 2 columns]

In [54]:
target.to_csv(resultado, index = False)