In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

In [2]:
auctions = pd.read_csv('auctions.csv.gzip', compression = 'gzip')

In [3]:
auctions.head()

,auction_type_id,country,date,device_id,platform,ref_type_id,source_id
0,NaN,6333597102633388268,2019-03-11 14:18:33.290763,6059599345986491085,1,1,0
1,NaN,6333597102633388268,2019-03-11 14:18:34.440157,1115994996230693426,1,1,0
2,NaN,6333597102633388268,2019-03-11 14:18:35.862360,7463856250762200923,1,1,0
3,NaN,6333597102633388268,2019-03-11 14:18:36.167163,7829815350267792040,1,1,0
4,NaN,6333597102633388268,2019-03-11 14:18:37.728590,1448534231953777480,1,1,0

In [4]:
auctions['auction_type_id'].count_values()

AttributeError: 'Series' object has no attribute 'count_values'

In [5]:
auctions['auction_type_id'].value_counts()

Series([], Name: auction_type_id, dtype: int64)

In [6]:
auctions.describe

<bound method NDFrame.describe of           auction_type_id              country                        date  \
0                     NaN  6333597102633388268  2019-03-11 14:18:33.290763
1                     NaN  6333597102633388268  2019-03-11 14:18:34.440157
2                     NaN  6333597102633388268  2019-03-11 14:18:35.862360
3                     NaN  6333597102633388268  2019-03-11 14:18:36.167163
4                     NaN  6333597102633388268  2019-03-11 14:18:37.728590
5                     NaN  6333597102633388268  2019-03-11 14:18:37.939485
6                     NaN  6333597102633388268  2019-03-11 14:18:39.285471
7                     NaN  6333597102633388268  2019-03-11 14:18:42.823963
8                     NaN  6333597102633388268  2019-03-11 14:18:43.587421
9                     NaN  6333597102633388268  2019-03-11 14:18:44.470248
10                    NaN  6333597102633388268  2019-03-11 14:18:47.603990
11                    NaN  6333597102633388268  2019-03-11 14:18:48.424327
12                    NaN  6333597102633388268  2019-03-11 14:18:48.700656
13                    NaN  6333597102633388268  2019-03-11 14:18:48.820769
14                    NaN  6333597102633388268  2019-03-11 14:18:48.989413
15                    NaN  6333597102633388268  2019-03-11 14:18:49.320024
16                    NaN  6333597102633388268  2019-03-11 14:18:49.501252
17                    NaN  6333597102633388268  2019-03-11 14:18:50.997590
18                    NaN  6333597102633388268  2019-03-11 14:18:52.492951
19                    NaN  6333597102633388268  2019-03-11 14:18:53.763975
20                    NaN  6333597102633388268  2019-03-11 14:18:54.439265
21                    NaN  6333597102633388268  2019-03-11 14:18:54.608819
22                    NaN  6333597102633388268  2019-03-11 14:19:03.096470
23                    NaN  6333597102633388268  2019-03-11 14:19:03.206564
24                    NaN  6333597102633388268  2019-03-11 14:19:05.317992
25                    NaN  6333597102633388268  2019-03-11 14:19:05.729600
26                    NaN  6333597102633388268  2019-03-11 14:19:07.947622
27                    NaN  6333597102633388268  2019-03-11 14:19:08.934501
28                    NaN  6333597102633388268  2019-03-11 14:19:09.383314
29                    NaN  6333597102633388268  2019-03-11 14:19:12.091253
...                   ...                  ...                         ...
19571289              NaN  6333597102633388268  2019-03-10 21:55:33.441782
19571290              NaN  6333597102633388268  2019-03-10 21:55:34.961737
19571291              NaN  6333597102633388268  2019-03-10 21:55:37.206321
19571292              NaN  6333597102633388268  2019-03-10 21:55:39.066762
19571293              NaN  6333597102633388268  2019-03-10 21:55:39.619017
19571294              NaN  6333597102633388268  2019-03-10 21:55:41.605773
19571295              NaN  6333597102633388268  2019-03-10 21:55:41.637262
19571296              NaN  6333597102633388268  2019-03-10 21:55:42.046556
19571297              NaN  6333597102633388268  2019-03-10 21:55:42.895444
19571298              NaN  6333597102633388268  2019-03-10 21:55:43.995997
19571299              NaN  6333597102633388268  2019-03-10 21:55:46.032485
19571300              NaN  6333597102633388268  2019-03-10 21:55:46.318415
19571301              NaN  6333597102633388268  2019-03-10 21:55:46.704812
19571302              NaN  6333597102633388268  2019-03-10 21:55:48.001953
19571303              NaN  6333597102633388268  2019-03-10 21:55:49.117482
19571304              NaN  6333597102633388268  2019-03-10 21:55:49.877293
19571305              NaN  6333597102633388268  2019-03-10 21:55:50.807369
19571306              NaN  6333597102633388268  2019-03-10 21:55:50.991245
19571307              NaN  6333597102633388268  2019-03-10 21:55:51.657568
19571308              NaN  6333597102633388268  2019-03-10 21:55:55.844928
19571309              NaN  6333597102633388268  2019-03-10 21:55:56.046065
19571310              NaN  6333597102633388268  2019-03-10 21:55:58.022745
19571311              NaN  6333597102633388268  2019-03-10 21:55:59.792450
19571312              NaN  6333597102633388268  2019-03-10 21:55:59.994127
19571313              NaN  6333597102633388268  2019-03-10 21:56:03.003286
19571314              NaN  6333597102633388268  2019-03-10 21:56:03.118171
19571315              NaN  6333597102633388268  2019-03-10 21:56:05.176260
19571316              NaN  6333597102633388268  2019-03-10 21:56:05.451091
19571317              NaN  6333597102633388268  2019-03-10 21:56:06.205785
19571318              NaN  6333597102633388268  2019-03-10 21:56:06.336654

                    device_id  platform  ref_type_id  source_id
0         6059599345986491085         1            1          0
1         1115994996230693426         1            1          0
2         7463856250762200923         1            1          0
3         7829815350267792040         1            1          0
4         1448534231953777480         1            1          0
5         1448534231953777480         1            1          0
6         7197160868095710320         1            1          0
7          160071254383181872         1            1          0
8          961481517958884390         1            1          0
9         2960551690927930513         1            1          0
10        6306824739731026067         1            1          0
11        3936313574333788462         1            1          0
12        1575029377278525470         1            1          0
13        6098258806045271615         1            1          0
14        8870127210564087341         1            1          0
15         937592113243669784         2            7          0
16        3936313574333788462         1            1          0
17        8120374343761443836         2            7          0
18        3742224377974451963         1            1          0
19        8324915702482685094         1            1          0
20        6841615430383729819         1            1          0
21        3634487069397178977         1            1          0
22        1877625370646254788         1            1          0
23        1187730740356458937         1            1          0
24        3696450219761307445         1            1          0
25        2312119613209372755         1            1          0
26        1877625370646254788         1            1          0
27        1877625370646254788         1            1          0
28        1529322310682744712         1            1          0
29         949789593533879408         1            1          0
...                       ...       ...          ...        ...
19571289  8637645156834210424         2            7          0
19571290   716010093844340461         1            1          0
19571291  3193036437293429257         1            1          0
19571292  4203906304790719718         1            1          0
19571293   716010093844340461         1            1          0
19571294  3543199377581972278         1            1          0
19571295  8952845892051149991         1            1          0
19571296  5357158140596236514         1            1          0
19571297  6281912427974433497         1            1          0
19571298  3552566591453288837         2            7          0
19571299  5314798245571670767         1            1          0
19571300  3257520451169874353         2            7          0
19571301  1992523781094933846         1            1          0
19571302  8544722613885411018         1            1          0
19571303  6265133289829753666         1            1          0
19571304  6105993161101792891         1            1          0
19571305  4702513746381426262         1            1          0
19571306  6673305222609765815         1            1          0
19571307  6281912427974433497         1            1          0
19571308  1822306438288043019         1            1          0
19571309  6788007717765727066         1            1          0
19571310  3767550830171929401         1            1          0
19571311  3593552000946132307         1            1          0
19571312  2809219529315804604         1            1          0
19571313  9137019521641615251         1            1          0
19571314  2050055804503401356         2            7          0
19571315  7439155813231556854         1            1          0
19571316  8433617772649884455         1            1          0
19571317  6074112720199809717         1            1          0
19571318  4271283232404461740         1            1          0

[19571319 rows x 7 columns]>

In [7]:
auctions['auction_type_id'].value_counts()

Series([], Name: auction_type_id, dtype: int64)

In [10]:
auctions.dtypes

auction_type_id    float64
country              int64
date                object
device_id            int64
platform             int64
ref_type_id          int64
source_id            int64
dtype: object

In [11]:
auctions['source_id'].value_counts()

0    13354597
1     4016739
5     1466494
2      582083
6      151406
Name: source_id, dtype: int64

In [12]:
auctions.columns

Index(['auction_type_id', 'country', 'date', 'device_id', 'platform',
       'ref_type_id', 'source_id'],
      dtype='object')

In [13]:
auctions['ref_type_id'].value_counts()

1    15541825
7     4029494
Name: ref_type_id, dtype: int64

In [14]:
auctions['platform'].value_counts()

1    15541825
2     4029494
Name: platform, dtype: int64

In [15]:
auctions['device_id'].value_counts()

633139769114048761     27762
7202276635029175071    23055
7298861376107043945    18188
6302840482782120473    16400
5376802567578262905    16367
8963711959081981780    14362
795159065504552200     12275
6841615430383729819    12077
5384039226444052914    11632
3198179064438296471    11565
519658456951133298     10541
2435544514359302887    10274
8751190726444323885    10256
1835469468095030098    10121
1800317677967270083    10036
9027154272484048876     9958
7574657722181550308     9767
5051610571898428259     9642
320899491737875154      9388
8292793494956750501     9315
201759600719985554      9158
8021195662481548645     9128
7650408579713341483     9020
6392567838173461255     8994
1478017482044456084     8839
6203407103275384250     8823
68016455690089173       8809
8496718680483076445     8682
8491787427844905567     8513
4834359787191717922     8495
                       ...
5751956180575781757        1
2048572451559832028        1
3744576664345883432        1
7367086705606121699        1
646535409008459333         1
6770910701982113580        1
2863959931991583508        1
2696817569245344530        1
7553430075553844653        1
4617307111815896778        1
5240339451295485635        1
4692566548344272637        1
35674910428474471          1
3159093650487986533        1
1942683830003570264        1
8019294471594894593        1
6869424683092918051        1
959426849812803471         1
1944088880283346077        1
6622057180348619453        1
3652020858507657809        1
6021685018865299736        1
6725662693426834602        1
6936985002156508492        1
8787642868763157961        1
6586001901497243197        1
4903599056466380772        1
9101372426762671929        1
4378253870857185347        1
5221298118515168096        1
Name: device_id, Length: 206977, dtype: int64

In [16]:
auctions['country'].value_counts()

6333597102633388268    19571319
Name: country, dtype: int64

In [18]:
auctions['auction_type_id'].isnull().sum()

19571319